# Generated by Django 3.0.8 on 2020-11-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20201117_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='paperclip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Paperclip'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='paperclip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.Paperclip'),
        ),
    ]
